### ISSUE TITLE
cannot download images

### ISSUE THREAD

**Issue by dev-lang** [morinokami/twitter-image-downloader#6]
every time i try to run the script i get this error:

Traceback (most recent call last):
  File "twt_img.py", line 192, in <module>
    downloader = Downloader(api_key, api_secret)
  File "twt_img.py", line 18, in __init__
    self.bearer_token = self.bearer(api_key, api_secret)
  File "twt_img.py", line 88, in bearer
    raise BearerTokenNotFetchedError()
exceptions.BearerTokenNotFetchedError

**Comment by morinokami** [comment]
@dev-lang That error may be related to your api key and secret. Did you create your app and generate api keys on Twitter's developer page? Go to [the website](https://developer.twitter.com/en/apps) and confirm that your "Consumer API keys" are generated.

**Comment by dev-lang** [comment]
i did... i created a file like this:

`{
    "api_key": "my api key from my app created on twitter developer is here",
    "api_secret": "same case for my api secret key"
}
`

i saved it as confidentials.json

then i run it as it and get this error> 

```
franco@plasma:~$ cd twitter-image-downloader/
franco@plasma:~/twitter-image-downloader$ ls
confidentials.json  __pycache__  requirements-dev.txt  test_app.py
exceptions.py       README.md    requirements.txt      twt_img.py
franco@plasma:~/twitter-image-downloader$ python3 twt_img.py 
usage: twt_img.py [-h] [-c CONFIDENTIALS] [-s {large,medium,small,thumb,orig}]
                  [-l LIMIT] [--rts]
                  user_id dest
twt_img.py: error: the following arguments are required: user_id, dest
franco@plasma:~/twitter-image-downloader$ python3 twt_img.py -c confidentials.json -s large theuseriwanttotakephotos thedestfolder
Traceback (most recent call last):
  File "twt_img.py", line 192, in <module>
    downloader = Downloader(api_key, api_secret)
  File "twt_img.py", line 18, in __init__
    self.bearer_token = self.bearer(api_key, api_secret)
  File "twt_img.py", line 88, in bearer
    raise BearerTokenNotFetchedError()
exceptions.BearerTokenNotFetchedError
franco@plasma:~/twitter-image-downloader$ 

```

**Comment by dev-lang** [comment]
i have this on my app:

`Consumer API keys
RANDOMCODE (API key)

RANDOMCODE (API secret key)


Regenerate
Access token & access token secret
RANDOMCODE (Access token)

RANDOMCODE (Access token secret)

Read and write (Access level)`

should i use consumer codes instead of access tokens?

**Comment by morinokami** [comment]
@dev-lang 
> should i use consumer codes instead of access tokens?

Yes. You need to supply the "Consumer API keys" to confidentials.json. Can you use consumer keys and try again?

**Comment by dev-lang** [comment]
done! now it works. but now it gives me another error:

```
Got 92 tweets
Saving http://pbs.twimg.com/media/EHhILkJXYAAaxdB.jpg
Saving http://pbs.twimg.com/ext_tw_video_thumb/1185677446886109185/pu/img/XIZVbbMgNI6EeXuk.jpg
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "twt_img.py", line 193, in <module>
    downloader.download_images(args.user_id, args.dest, args.size, args.limit, args.rts)
  File "twt_img.py", line 55, in download_images
    self.save_image(image, save_dest, fname, size)
  File "twt_img.py", line 161, in save_image
    r = requests.get(image + ':' + size, stream=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
is normal? its looks like a network error (RemoteDisconnected) but i'm not sure if it is an error from the side of twitter or my side.

**Comment by dev-lang** [comment]
solved! changed my networks and now it works fine!

**Comment by morinokami** [comment]
Glad you solved the issue 😄
